image: python:latest


test:
  tags:
    - docker-linux
  script:
    - pip install tox  # you can also use tox
    - tox -e lint,unitest,type
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'


build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  tags:
    - docker-linux

  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
      --skip-tls-verify
  only:
    - main
